### ISSUE TITLE
Error PHP8 - CoffeeCode - Router

### ISSUE THREAD

**Issue by joriseduardo** [robsonvleite/router#44]
No ultimo uptade, comecou a ocorrer o seguinte erro.

PHP Fatal error:  Uncaught TypeError: CoffeeCode\Router\Dispatch::handler(): Argument #2 ($namespace) must be of type string, null given, called in /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/RouterTrait.php on line 52 and defined in /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/RouterTrait.php:170
Stack trace:
#0 /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/RouterTrait.php(52): CoffeeCode\Router\Dispatch->handler(Object(Closure), NULL)
#1 /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/RouterTrait.php(59): CoffeeCode\Router\Dispatch->CoffeeCode\Router\{closure}()
#2 /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/Router.php(38): CoffeeCode\Router\Dispatch->addRoute('GET', '', Object(Closure), NULL, NULL)
#3 /shared/httpd/mobbilizanew/htdocs/index.php(14): CoffeeCode\Router\Router->get('/', Object(Closure))
#4 {main}
  thrown in /shared/httpd/mobbilizanew/htdocs/vendor/coffeecode/router/src/RouterTrait.php on line 170

**Comment by joriseduardo** [comment]
Saquei na verdade precisa setar o namespace agora
